---
title: "Miscellaneous"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Routine

**Load:**

```{r,eval=FALSE}
# load
setwd("./prelim/")
library(workflowr)
```

**WorkflowR publish:**

```{r,eval=FALSE}
# workflowR publish
wflow_publish("./notes/*.Rmd")
```

**Cleanup:**

```{r,eval=FALSE}
# cleanup environment
rm(list = ls())
```

**Git commit and push:**

```{bash,eval=FALSE}
# git pull
#mkdir ./prelim/
#cd ./prelim/ 
#git init
#git pull git@github.com:chenh19/prelim.git

# git push
#cd ./prelim/
#git remote add origin git@github.com:chenh19/prelim.git
git commit -a -m "update"
git add --all
git commit -a -m "update"
git push -u origin main
```

**Environment:** [Kubuntu 22.04 LTS](https://kubuntu.org/); [Setup Shell Scripts](https://github.com/chenh19/MyWorkspace)  
**Git SSH configuration:** [```git_ssh_config.sh```](https://raw.githubusercontent.com/chenh19/rotation2/main/code/0_prepare/git_ssh_config.sh) (Ref: [YouTube](https://youtu.be/YnSMYgIybFU))  


### 2. Instructions

- [Prelim instructions](https://chenh19.github.io/prelim/GGSB_questions_2022/MISC/GGSB_Prelim_Exam_Instructions.pdf)  
- [Prelim information](https://chenh19.github.io/prelim/GGSB_questions_2022/MISC/PrelimExam_Information_from_GGSB_Handbook.pdf)  


### 3. Other questions

- [Questions not selected](https://chenh19.github.io/prelim/questions_not_selected.html)


### 4. Schedule

- Prelim exam time: week of ```9/12/2022``` (can move up)
