---
title: "Question-2"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
    toc_depth: 4
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Materials

- [**Question-2**](https://chenh19.github.io/prelim/GGSB_questions_2022/GGSB_Question_2/GGSB_Prelim_Question_2.pdf) (by [Bruce Lahn](https://profiles.uchicago.edu/profiles/display/38462))
- **Q2 refs: ** [Ref-1](https://chenh19.github.io/prelim/GGSB_questions_2022/GGSB_Question_2/Question_2-Reference_1.pdf), 
                [Ref-2](https://chenh19.github.io/prelim/GGSB_questions_2022/GGSB_Question_2/Question_2-Reference_2.pdf), 
                [Ref-3](https://chenh19.github.io/prelim/GGSB_questions_2022/GGSB_Question_2/Question_2-Reference_3.pdf)  


### Questions

As a concept, **gene therapy** has been around for decades. But it has only recently emerged as an effective therapeutic modality with a number of drugs getting approved in the last few years. With gene therapy finally moving beyond the proof-of-concept stage, the field is poised to flourish, with many previously incurable diseases now expected to have complete cures in the coming years.  

1. Please describe the **major classes of diseases targeted by gene therapy** either as approved treatments or at the research stage. Please **explain why** these diseases are particularly conducive to gene therapy. Conversely, please describe what types of diseases are not conducive to gene therapy at present and why.  

2. What are the **major limitations and challenges** in the effective use of gene therapy?  

3. **Lentivirus** (**LV**) and **adeno-associated virus** (**AAV**) are currently the most popular gene therapy vectors. Please describe the **pros** and **cons** of LV and AAV, and what **types of diseases** they are each suitable for.  


### Slides

- [**Q2_HC.pptx](https://chenh19.github.io/prelim/slides/Q2/Q2_HC.pptx)
- [**Q2_HC.pdf](https://chenh19.github.io/prelim/slides/Q2/Q2_HC.pdf)
